//
//  IAP_EVENT.h
//  NaviUtil
//
//  Created by Coming on 8/31/14.
//  Copyright (c) 2014 Coming. All rights reserved.
//

#ifndef NaviUtil_IAP_EVENT_h
#define NaviUtil_IAP_EVENT_h


#define IAP_EVENT_COMPLETE_TRANSACTION  @"IAP_EVENT_COMPLETE_TRANSACTION"
#define IAP_EVENT_RESTORE_TRANSACTION   @"IAP_EVENT_RESTORE_TRANSACTION"
#define IAP_EVENT_TRANSACTION_FAILED    @"IAP_EVENT_TRANSACTION_FAILED"

#define IAP_EVENT_IAP_STATUS_RETRIEVING     @"IAP_STATUS_RETRIEVING"
#define IAP_EVENT_IAP_STATUS_RETRIEVED      @"IAP_STATUS_RETRIEVED"
#define IAP_EVENT_IAP_STATUS_RETRIEVE_FAIL  @"IAP_STATUS_RETRIEVE_FAIL"

#endif
